language: node_js
node_js:
    - "10.16.0"
cache: yarn
install: 
    - yarn install
jobs:
    include:
      - stage: Test my Package
        script:
            - yarn test
            - yarn coverage
      - stage: Release my Package
        deploy:
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            skip_cleanup: true
            on:
                tags: true       