language: node_js
node_js:
    - "10.16.0"

script: echo "Running tests against $(node -v) ..."

jobs:
    include:
      - stage: npm release
        node_js: "10.16.0"
        script: echo "Deploying to npm ..."
        deploy:
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            on:
                tags: true