language: node_js
node_js:
    - "10.16.0"
cache: yarn
install: 
    - yarn install
script:
    - yarn test
    - yarn coverage
jobs:
    include:
        - stage: npm release
        deploy:
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            skip_cleanup: true
            on:
                tags: true
branches:
    only:
        - master